/**
 * Connecting a CircleCI project.
 *
 * CircleCI webhooks are configured per project in Project Settings → Webhooks.
 * The secret is generated by DevAnalytics and pasted there; CircleCI signs the
 * body with it as HMAC-SHA256.
 */

/** Events a connected project must send. */
export const REQUIRED_CIRCLECI_EVENTS = ['workflow-completed'] as const;

/**
 * `job-completed` is deliberately not requested. Jobs are the stages inside a
 * workflow, and ingesting them would count every metric derived from runs once
 * per stage.
 */
export const IGNORED_CIRCLECI_EVENTS = ['job-completed'] as const;

export interface CircleCiWebhookConfig {
  name: string;
  url: string;
  events: string[];
  'signing-secret': string;
  'verify-tls': boolean;
}

export function circleciWebhookConfig(input: { url: string; secret: string; name?: string }): CircleCiWebhookConfig {
  return {
    name: input.name ?? 'DevAnalytics',
    url: input.url,
    events: [...REQUIRED_CIRCLECI_EVENTS],
    'signing-secret': input.secret,
    'verify-tls': true,
  };
}

/**
 * What CircleCI cannot tell us, stated once so it is not rediscovered.
 *
 * These are properties of CircleCI's webhook payloads, not gaps in the
 * adapter. Each is handled by leaving the value unknown rather than guessing.
 */
export const CIRCLECI_LIMITATIONS = [
  'No runner queue time. The payload reports when a workflow was created and when it stopped, never how long it waited, so ci_queue_time excludes CircleCI runs rather than recording them as instant.',
  'No pull request number. Runs are linked to a pull request through the commit they built, so a CircleCI run on a commit that is not on any pull request stays unlinked.',
  'No code host repository id. Repositories are resolved by host and path, which is why a CircleCI project must correspond to a repository connected through GitHub or GitLab.',
  'No stable actor. Commit authors appear as a name and an email with no host user id, so CI runs carry no actor rather than inventing duplicate developers.',
  'Bitbucket-hosted projects are ignored, because this platform does not model Bitbucket as a code host and attributing them to the wrong host would be worse than dropping them.',
] as const;
